src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bundle\MakerBundle\Str;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 * @UniqueEntity(
 *     fields={"first_name", "middle_name","last_name"},
 *     errorPath="last_name",
 *     message="Такой автор уже существует в каталоге"
 * )
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $middle_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="У автора должна быть фамилия")
     */
    private $last_name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Book", mappedBy="authors")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->middle_name;
    }

    public function setMiddleName(?string $middle_name): self
    {
        $this->middle_name = $middle_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            $book->removeAuthor($this);
        }

        return $this;
    }

    public function __toString()
    {
        /*
         * if use one field $this->full_name:
         *
         * $names = explode(' ', $this->full_name);
         * $display_name = array_shift($names);
         * $display_name .= " ".implode(' ',array_map(function($name){
         *   return mb_strtoupper(mb_substr($name,0,1)).".";
         * },$names));
         * return $display_name;
         *
         * */

        return $this->last_name .
            (!empty($this->first_name) ? " " . mb_strtoupper(mb_substr($this->first_name, 0, 1))."." : "") .
            (!empty($this->middle_name) ? " " . mb_strtoupper(mb_substr($this->middle_name, 0, 1))."." : "");
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('middle_name')
            ->add('last_name')
            ->add('books')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/author")
 */
class AuthorController extends AbstractController
{
    /**
     * @Route("/", name="author_index", methods={"GET"})
     */
    public function index(AuthorRepository $authorRepository): Response
    {
        return $this->render('author/index.html.twig', [
            'authors' => $authorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="author_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($author);
            $entityManager->flush();

            return $this->redirectToRoute('author_index');
        }

        return $this->render('author/new.html.twig', [
            'author' => $author,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="author_show", methods={"GET"})
     */
    public function show(Author $author): Response
    {
        return $this->render('author/show.html.twig', [
            'author' => $author,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="author_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Author $author): Response
    {
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('author_index');
        }

        return $this->render('author/edit.html.twig', [
            'author' => $author,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="author_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Author $author): Response
    {
        if ($this->isCsrfTokenValid('delete'.$author->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($author);
            $entityManager->flush();
        }

        return $this->redirectToRoute('author_index');
    }
}

templates/author/_delete_form.html.twig
<form method="post" action="{{ path('author_delete', {'id': author.id}) }}" onsubmit="return confirm('Вы действительно хотите стереть этого автора?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ author.id) }}">
    <button class="btn">Удалить</button>
</form>

templates/author/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Сохранить') }}</button>
{{ form_end(form) }}

templates/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактировать автора{% endblock %}

{% block body %}
    <h1>Редактировать автора</h1>

    {{ include('author/_form.html.twig', {'button_label': 'Сохранить'}) }}

    <a href="{{ path('author_index') }}">Назад к спискуt</a>

    {{ include('author/_delete_form.html.twig') }}
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Список авторов{% endblock %}

{% block body %}
    <h1>Список авторов</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>Фамилия</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for author in authors %}
            <tr>
                <td>{{ author.id }}</td>
                <td>{{ author.firstName }}</td>
                <td>{{ author.middleName }}</td>
                <td>{{ author.lastName }}</td>
                <td>
                    <a href="{{ path('author_show', {'id': author.id}) }}">показать</a>
                    <a href="{{ path('author_edit', {'id': author.id}) }}">изменить</a>
                    <a href="{{ path('author_delete', {'id': author.id}) }}">удалить</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">еще нет ни одного автора</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('author_new') }}">Create new</a>
{% endblock %}

templates/author/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новый автор{% endblock %}

{% block body %}
    <h1>Сохранить автора</h1>

    {{ include('author/_form.html.twig') }}

    <a href="{{ path('author_index') }}">Назад к списку</a>
{% endblock %}

templates/author/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Автор{% endblock %}

{% block body %}
    <h1>Автор</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ author.id }}</td>
            </tr>
            <tr>
                <th>Имя</th>
                <td>{{ author.firstName }}</td>
            </tr>
            <tr>
                <th>Отчество</th>
                <td>{{ author.middleName }}</td>
            </tr>
            <tr>
                <th>Фамилия</th>
                <td>{{ author.lastName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('author_index') }}">Назад к списку</a>

    <a href="{{ path('author_edit', {'id': author.id}) }}">Редактировать</a>

    {{ include('author/_delete_form.html.twig') }}
{% endblock %}